# Generated by Django 4.1 on 2023-12-19 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_cart_instamojo_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now_add=True)),
                ("coupon_code", models.CharField(max_length=100)),
                ("is_expired", models.BooleanField(default=False)),
                ("discount_price", models.IntegerField(default=50)),
                ("minimun_ammount", models.IntegerField(default=300)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
