# Generated by Django 4.1 on 2024-01-09 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-order_date']},
        ),
        migrations.AddField(
            model_name='cart',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
